# Generated by Django 4.2.11 on 2024-04-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(blank=True, default=' ', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Title_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Course_about_text', models.TextField(blank=True, null=True)),
                ('course_image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
            ],
        ),
        migrations.CreateModel(
            name='Learning_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic_Name', models.CharField(blank=True, default=' ', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
            ],
        ),
        migrations.CreateModel(
            name='Puropse_of_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('Purpose_Text', models.CharField(blank=True, default=' ', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_openion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('Student_name', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('Openion_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Title_Name', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('Question_Answer_Text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('Teacher_name', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('Teacher_position', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('Teacher_About_text', models.TextField()),
            ],
        ),
    ]
