# Generated by Django 4.2.11 on 2024-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page_Two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_All_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info_Title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Left_text', models.TextField(blank=True, default=' ', null=True)),
                ('Right_text', models.TextField(blank=True, default=' ', null=True)),
            ],
        ),
    ]
