# Generated by Django 4.2.11 on 2024-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page_Two', '0003_all_course_data_header_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_all_data',
            name='Right_text',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
    ]
