# Generated by Django 4.2.11 on 2024-04-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0022_alter_all_category_card_data_options_and_more'),
        ('Home_Page_Two', '0005_alter_all_course_data_header_name_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_summery_text', models.TextField(blank=True, default=' ', null=True)),
                ('Category_image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='Deshboard.cattegorymodel')),
            ],
            options={
                'verbose_name': 'CourseInfo',
                'verbose_name_plural': 'CourseInfo',
            },
        ),
        migrations.DeleteModel(
            name='Heading_title',
        ),
    ]
