# Generated by Django 4.2.11 on 2024-04-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0022_alter_all_category_card_data_options_and_more'),
        ('Home_Page_Two', '0006_courseinfo_delete_heading_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Wise_Card_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default=' ', null=True, upload_to='Deshboard/media/')),
                ('Course_name', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('student_review', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('Course_fees', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('Select_Category', models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Select_Category', to='Deshboard.cattegorymodel')),
            ],
            options={
                'verbose_name': 'Category_Wise_Card_Data',
                'verbose_name_plural': 'Category_Wise_Card_Data',
            },
        ),
    ]
