# Generated by Django 4.2.11 on 2024-04-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page_Two', '0009_delete_course_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning_topic',
            old_name='Topic_Name',
            new_name='Learning_Topics',
        ),
    ]
