# Generated by Django 4.2.11 on 2024-05-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0023_all_category_model_slug'),
        ('Home_Page_Two', '0010_rename_topic_name_learning_topic_learning_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_Name_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_number_and_Title', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': 'Module_Name_Number',
                'verbose_name_plural': 'Module_Name_Number',
            },
        ),
        migrations.CreateModel(
            name='Module_Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week_name', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': 'Module_Week',
                'verbose_name_plural': 'Module_Week',
            },
        ),
        migrations.CreateModel(
            name='Module_Video_And_PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_Title', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('video', models.FileField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/video/')),
                ('PDF_And_Docs', models.FileField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/pdf_Docs/')),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
                ('select_Module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home_Page_Two.module_name_number')),
                ('select_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home_Page_Two.module_week')),
            ],
            options={
                'verbose_name': 'Module_Video_And_PDF',
                'verbose_name_plural': 'Module_Video_And_PDF',
            },
        ),
        migrations.AddField(
            model_name='module_name_number',
            name='select_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home_Page_Two.module_week'),
        ),
    ]
