# Generated by Django 4.2.11 on 2024-05-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0024_delete_home_cattegory_wise_show_card_detial_and_more'),
        ('Home_Page_Two', '0011_module_name_number_module_week_module_video_and_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_wise_card_data',
            name='Select_Category',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Select_Category', to='Deshboard.all_category_model'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='Deshboard.all_category_model'),
        ),
    ]
