# Generated by Django 4.2.11 on 2024-05-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page_Two', '0012_alter_category_wise_card_data_select_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module_video_and_pdf',
            name='PDF_And_Docs',
        ),
        migrations.DeleteModel(
            name='Category_Wise_Card_Data',
        ),
    ]
