# Generated by Django 4.2.11 on 2024-05-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page_Two', '0013_remove_module_video_and_pdf_pdf_and_docs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_title',
            old_name='chooes_Category',
            new_name='chooes_Course',
        ),
    ]
