# Generated by Django 4.2.11 on 2024-05-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page_Two', '0015_delete_courseinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_course_data_header_name',
            options={'verbose_name': '2. Create Course Detials Title', 'verbose_name_plural': '2. Create Course Detials Title'},
        ),
        migrations.AlterModelOptions(
            name='course_all_data',
            options={'verbose_name': '3. Title Wise Show Data', 'verbose_name_plural': '3. Title Wise Show Data'},
        ),
        migrations.AlterModelOptions(
            name='course_title',
            options={'verbose_name': '1. Course Header About', 'verbose_name_plural': '1. Course Header About'},
        ),
        migrations.AlterModelOptions(
            name='learning_topic',
            options={'verbose_name': '12. EveryThing in this course', 'verbose_name_plural': '12. EveryThing in this course'},
        ),
        migrations.AlterModelOptions(
            name='module_name_number',
            options={'verbose_name': '6. Set Week Wise Module ', 'verbose_name_plural': '6. Set Week Wise Module '},
        ),
        migrations.AlterModelOptions(
            name='module_video_and_pdf',
            options={'verbose_name': '7. Set Module Wise video ', 'verbose_name_plural': '7. Set Module Wise video '},
        ),
        migrations.AlterModelOptions(
            name='module_week',
            options={'verbose_name': ' 5. Set Module Week', 'verbose_name_plural': ' 5. Set Module Week'},
        ),
        migrations.AlterModelOptions(
            name='project_image',
            options={'verbose_name': '8. Project Image', 'verbose_name_plural': '8. Project Image'},
        ),
        migrations.AlterModelOptions(
            name='puropse_of_course',
            options={'verbose_name': '4. Puropse of course Deta Set', 'verbose_name_plural': '4. Puropse of course Deta Set'},
        ),
        migrations.AlterModelOptions(
            name='student_openion',
            options={'verbose_name': '9. Student openion', 'verbose_name_plural': '9. Student openion'},
        ),
        migrations.AlterModelOptions(
            name='student_question',
            options={'verbose_name': ' 11. Student Course Related Question And Answer', 'verbose_name_plural': ' 11. Student Course Related Question And Answer'},
        ),
        migrations.AlterModelOptions(
            name='teacher_about',
            options={'verbose_name': '10. Course Teacher About', 'verbose_name_plural': '10. Course Teacher About'},
        ),
    ]
