# Generated by Django 4.2.11 on 2024-04-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li_text', models.CharField(blank=True, max_length=300, null=True)),
                ('header_name_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.footer_other_detail_header')),
            ],
        ),
    ]
