# Generated by Django 4.2.11 on 2024-04-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_footer_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer_list',
        ),
    ]
