# Generated by Django 4.2.11 on 2024-04-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_delete_footer_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_li',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List_Data', models.CharField(blank=True, max_length=300, null=True)),
                ('HeaderChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.footer_other_detail_header')),
            ],
        ),
    ]
