# Generated by Django 4.2.11 on 2024-04-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_cattegory_name_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CattegoryWiseShowHeaderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattegoryName', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cattegory_Wise_Show_Card_Detial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_image', models.ImageField(blank=True, null=True, upload_to='Deshboard/media/')),
                ('Course_name', models.CharField(blank=True, max_length=150, null=True)),
                ('student_reviews', models.CharField(blank=True, default='  ', max_length=150, null=True)),
                ('Course_fee', models.PositiveIntegerField()),
                ('Choice_category_header_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.cattegorywiseshowheadername')),
            ],
        ),
    ]
