# Generated by Django 4.2.11 on 2024-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_cattegorywiseshowheadername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattegory_wise_show_card_detial',
            name='Card_image',
            field=models.ImageField(blank=True, null=True, upload_to='HomePage/media/'),
        ),
    ]
