# Generated by Django 4.2.11 on 2024-04-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_alter_cattegory_wise_show_card_detial_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminer_Page_Seminer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, default=' ', max_length=10, null=True)),
                ('month', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('year', models.CharField(blank=True, default=' ', max_length=10, null=True)),
                ('seminer_subject', models.CharField(blank=True, default=' ', max_length=150, null=True)),
                ('seminer_time', models.CharField(blank=True, default=' ', max_length=100, null=True)),
            ],
        ),
    ]
