# Generated by Django 4.2.11 on 2024-04-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_seminer_page_seminer_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminer_page_seminer_model',
            name='year',
        ),
    ]
