# Generated by Django 4.2.11 on 2024-04-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0009_remove_seminer_page_seminer_model_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cattegory_name_image',
            options={'verbose_name': 'Cattegory_Name_image', 'verbose_name_plural': 'Cattegory_Name_image'},
        ),
        migrations.AlterModelOptions(
            name='cattegory_wise_show_card_detial',
            options={'verbose_name': 'Cattegory_Wise_Show_Card_Detial', 'verbose_name_plural': 'Cattegory_Wise_Show_Card_Detial'},
        ),
        migrations.AlterModelOptions(
            name='cattegorywiseshowheadername',
            options={'verbose_name': 'CattegoryWiseShowHeaderName', 'verbose_name_plural': 'CattegoryWiseShowHeaderName'},
        ),
        migrations.AlterModelOptions(
            name='footer_last_section',
            options={'verbose_name': 'Footer_Last_section', 'verbose_name_plural': 'Footer_Last_section'},
        ),
        migrations.AlterModelOptions(
            name='footer_other_detail_header',
            options={'verbose_name': 'Footer_other_detail_header', 'verbose_name_plural': 'Footer_other_detail_header'},
        ),
        migrations.AlterModelOptions(
            name='header_li',
            options={'verbose_name': 'Header_li', 'verbose_name_plural': 'Header_li'},
        ),
        migrations.AlterModelOptions(
            name='navbar_text',
            options={'verbose_name': 'Navbar_text', 'verbose_name_plural': 'Navbar_text'},
        ),
        migrations.AlterModelOptions(
            name='payment_merchant',
            options={'verbose_name': 'Payment_Merchant', 'verbose_name_plural': 'Payment_Merchant'},
        ),
        migrations.AlterModelOptions(
            name='seminer_page_seminer_model',
            options={'verbose_name': 'Seminer_Page_Seminer_Model', 'verbose_name_plural': 'Seminer_Page_Seminer_Model'},
        ),
    ]
