# Generated by Django 4.2.11 on 2024-05-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0010_alter_cattegory_name_image_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cattegory_Name_image',
        ),
        migrations.DeleteModel(
            name='Cattegory_Wise_Show_Card_Detial',
        ),
        migrations.DeleteModel(
            name='CattegoryWiseShowHeaderName',
        ),
    ]
