# Generated by Django 4.2.11 on 2024-05-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0011_delete_cattegory_name_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seminer_Page_Seminer_Model',
            new_name='Seminer_Time',
        ),
        migrations.AlterModelOptions(
            name='seminer_time',
            options={'verbose_name': 'Seminer_Time', 'verbose_name_plural': 'Seminer_Time'},
        ),
    ]
