# Generated by Django 4.2.11 on 2024-05-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0012_rename_seminer_page_seminer_model_seminer_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminer_time',
            old_name='month',
            new_name='month_Year',
        ),
    ]
