# Generated by Django 4.2.11 on 2024-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0014_seminer_time_seminer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminer_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminer_image', models.ImageField(blank=True, default=' ', null=True, upload_to='HomePage/media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='seminer_time',
            name='seminer_image',
        ),
    ]
