# Generated by Django 4.2.11 on 2024-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0015_seminer_image_remove_seminer_time_seminer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminer_image',
            name='seminer_text',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
