# Generated by Django 4.2.11 on 2024-05-04 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0027_alter_all_category_card_data_options_and_more'),
        ('HomePage', '0017_seminer_image_text_delete_seminer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_summery_text', models.TextField(blank=True, default=' ', null=True)),
                ('Category_image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='Deshboard.all_category_model')),
            ],
            options={
                'verbose_name': 'Category Page Top Data',
                'verbose_name_plural': 'Category Page Top Data',
            },
        ),
    ]
