# Generated by Django 4.2.11 on 2024-05-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0018_courseinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer_last_section',
            options={'verbose_name': 'Footer warning site', 'verbose_name_plural': 'Footer warning site'},
        ),
        migrations.AlterModelOptions(
            name='footer_other_detail_header',
            options={'verbose_name': 'Footer Other Detail Title', 'verbose_name_plural': 'Footer Other Detail Title'},
        ),
        migrations.AlterModelOptions(
            name='header_li',
            options={'verbose_name': 'Footer Other Detail Title Data', 'verbose_name_plural': 'Footer Other Detail Title Data'},
        ),
        migrations.AlterModelOptions(
            name='navbar_text',
            options={'verbose_name': 'Latest Navbar News Text', 'verbose_name_plural': 'Latest Navbar News Text'},
        ),
        migrations.AlterModelOptions(
            name='payment_merchant',
            options={'verbose_name': 'Payment Merchent Image', 'verbose_name_plural': 'Payment Merchent Image'},
        ),
        migrations.AlterModelOptions(
            name='seminer_image_text',
            options={'verbose_name': 'Set Home Page Seminer Image', 'verbose_name_plural': 'Set Home Page Seminer Image'},
        ),
        migrations.AlterModelOptions(
            name='seminer_time',
            options={'verbose_name': 'Set Online Seminer Time', 'verbose_name_plural': 'Set Online Seminer Time'},
        ),
    ]
