# Generated by Django 4.2.11 on 2024-04-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecattegorywiseshow',
            name='choicecategory',
            field=models.ManyToManyField(to='Deshboard.homecattegorywiseshowsec'),
        ),
    ]
