# Generated by Django 4.2.11 on 2024-04-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0002_homecattegorywiseshow_choicecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecattegorywiseshow',
            name='choicecategory',
        ),
        migrations.AddField(
            model_name='homecattegorywiseshow',
            name='choicecategory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.homecattegorywiseshowsec'),
            preserve_default=False,
        ),
    ]
