# Generated by Django 4.2.11 on 2024-04-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0003_remove_homecattegorywiseshow_choicecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInstituteBannersecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_Title', models.CharField(blank=True, max_length=150, null=True)),
                ('Banner_Text', models.TextField(blank=True, null=True)),
                ('Banner_image', models.ImageField(blank=True, null=True, upload_to='Deshboard/media/')),
            ],
        ),
    ]
