# Generated by Django 4.2.11 on 2024-04-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0004_homeinstitutebannersecond'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOurServicesec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='homeourservice',
            name='service_text',
        ),
    ]
