# Generated by Django 4.2.11 on 2024-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0006_remove_homeourservice_serviceplayimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeourservice',
            name='SercicebannerImage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Deshboard/media/'),
        ),
        migrations.AlterField(
            model_name='homeourservice',
            name='Sercicebannervideo',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='Deshboard/media/video'),
        ),
    ]
