# Generated by Django 4.2.11 on 2024-04-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0007_alter_homeourservice_sercicebannerimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeourservice',
            name='Sercicebannervideo',
            field=models.FileField(blank=True, default='', null=True, upload_to='Deshboard/media/video'),
        ),
        migrations.AlterField(
            model_name='homeourservice',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
