# Generated by Django 4.2.11 on 2024-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0010_alter_homeseminermodel_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeseminermodel',
            name='day',
            field=models.PositiveIntegerField(default=' '),
        ),
        migrations.AlterField(
            model_name='homeseminermodel',
            name='month',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='homeseminermodel',
            name='seminer_image',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='Deshboard/media/'),
        ),
    ]
