# Generated by Django 4.2.11 on 2024-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0011_alter_homeseminermodel_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeseminermodel',
            name='year',
            field=models.PositiveIntegerField(default=' '),
        ),
    ]
