# Generated by Django 4.2.11 on 2024-04-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0012_alter_homeseminermodel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeseminermodel',
            name='seminer_subject',
            field=models.CharField(blank=True, default=' ', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homeseminermodel',
            name='seminer_time',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
