# Generated by Django 4.2.11 on 2024-04-18 15:44

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0013_homeseminermodel_seminer_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_title', models.CharField(blank=True, default=' ', max_length=150, null=True)),
                ('Banner_text', models.TextField(blank=True, default=' ', null=True)),
                ('Banner_video', embed_video.fields.EmbedVideoField(blank=True, default=' ', null=True)),
            ],
        ),
    ]
