# Generated by Django 4.2.11 on 2024-04-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0014_bannermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Category_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, default=' ', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='All_Category_Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default=' ', null=True, upload_to='Deshboard/media/')),
                ('Course_name', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('student_review', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('Course_fees', models.IntegerField(blank=True, default=' ', null=True)),
                ('Category_Name', models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_model')),
            ],
        ),
    ]
