# Generated by Django 4.2.11 on 2024-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0015_all_category_model_all_category_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_category_second',
            name='Cattegory_top_text',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
