# Generated by Django 4.2.11 on 2024-04-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0019_home_cattegory_wise_show_card_detial_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_Category_Second',
            new_name='All_Category_Card_Data',
        ),
    ]
