# Generated by Django 4.2.11 on 2024-04-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0020_rename_all_category_second_all_category_card_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_category_card_data',
            name='Course_fees',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
