# Generated by Django 4.2.11 on 2024-04-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0021_alter_all_category_card_data_course_fees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_category_card_data',
            options={'verbose_name': 'All_Category_Card_Data', 'verbose_name_plural': 'All_Category_Card_Data'},
        ),
        migrations.AlterModelOptions(
            name='all_category_model',
            options={'verbose_name': 'All_Category_model', 'verbose_name_plural': 'All_Category_model'},
        ),
        migrations.AlterModelOptions(
            name='all_category_text',
            options={'verbose_name': 'All_category_text', 'verbose_name_plural': 'All_category_text'},
        ),
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name': 'BannerModel', 'verbose_name_plural': 'BannerModel'},
        ),
        migrations.AlterModelOptions(
            name='cattegorymodel',
            options={'verbose_name': 'CattegoryModel', 'verbose_name_plural': 'CattegoryModel'},
        ),
        migrations.AlterModelOptions(
            name='home_cattegory_wise_show_card_detial',
            options={'verbose_name': 'Home_Cattegory_Wise_Show_Card_Detial', 'verbose_name_plural': 'Home_Cattegory_Wise_Show_Card_Detial'},
        ),
        migrations.AlterModelOptions(
            name='homecattegorywiseshowsec',
            options={'verbose_name': 'HomeCattegoryWiseShowsec', 'verbose_name_plural': 'HomeCattegoryWiseShowsec'},
        ),
        migrations.AlterModelOptions(
            name='homeevent',
            options={'verbose_name': 'HomeEvent', 'verbose_name_plural': 'HomeEvent'},
        ),
        migrations.AlterModelOptions(
            name='homeexpertteacher',
            options={'verbose_name': 'HomeExpertTeacher', 'verbose_name_plural': 'HomeExpertTeacher'},
        ),
        migrations.AlterModelOptions(
            name='homeinstitutebanner',
            options={'verbose_name': 'HomeInstituteBanner', 'verbose_name_plural': 'HomeInstituteBanner'},
        ),
        migrations.AlterModelOptions(
            name='homeinstitutebannersecond',
            options={'verbose_name': 'HomeInstituteBannersecond', 'verbose_name_plural': 'HomeInstituteBannersecond'},
        ),
        migrations.AlterModelOptions(
            name='homeourservice',
            options={'verbose_name': 'HomeOurService', 'verbose_name_plural': 'HomeOurService'},
        ),
        migrations.AlterModelOptions(
            name='homeourservicesec',
            options={'verbose_name': 'HomeOurServicesec', 'verbose_name_plural': 'HomeOurServicesec'},
        ),
        migrations.AlterModelOptions(
            name='homeseminermodel',
            options={'verbose_name': 'HomeSeminerModel', 'verbose_name_plural': 'HomeSeminerModel'},
        ),
        migrations.AlterModelOptions(
            name='homestudentopenion',
            options={'verbose_name': 'HomeStudentOpenion', 'verbose_name_plural': 'HomeStudentOpenion'},
        ),
    ]
