# Generated by Django 4.2.11 on 2024-05-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0023_all_category_model_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_Cattegory_Wise_Show_Card_Detial',
        ),
        migrations.DeleteModel(
            name='HomeCattegoryWiseShowsec',
        ),
    ]
