# Generated by Django 4.2.11 on 2024-05-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page_Two', '0012_alter_category_wise_card_data_select_category_and_more'),
        ('Deshboard', '0024_delete_home_cattegory_wise_show_card_detial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CattegoryModel',
        ),
        migrations.AddField(
            model_name='all_category_model',
            name='Category_Image',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='Deshboard/media/'),
        ),
    ]
