# Generated by Django 4.2.11 on 2024-05-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0026_rename_homeourservicesec_our_service_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_category_card_data',
            options={'verbose_name': '4.2 All Category Card Data', 'verbose_name_plural': '4.2 All Category Card Data'},
        ),
        migrations.AlterModelOptions(
            name='all_category_model',
            options={'verbose_name': '4.1 All Category Name and Image', 'verbose_name_plural': '4.1 All Category Name and Image'},
        ),
        migrations.AlterModelOptions(
            name='all_category_text',
            options={'verbose_name': '4. All Course Heading Text', 'verbose_name_plural': '4. All Course Heading Text'},
        ),
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name': '2. Banner Model', 'verbose_name_plural': '2. Banner Model'},
        ),
        migrations.AlterModelOptions(
            name='homeevent',
            options={'verbose_name': '10. Institute Event Image', 'verbose_name_plural': '10. Institute Event Image'},
        ),
        migrations.AlterModelOptions(
            name='homeexpertteacher',
            options={'verbose_name': '11. Teacher Information ', 'verbose_name_plural': '11. Teacher Information '},
        ),
        migrations.AlterModelOptions(
            name='homeinstitutebanner',
            options={'verbose_name': '8. Institute Banner left Image', 'verbose_name_plural': '8. Institute Banner left Image'},
        ),
        migrations.AlterModelOptions(
            name='homeinstitutebannersecond',
            options={'verbose_name': '8.1 Institute Banner Right Image', 'verbose_name_plural': '8.1 Institute Banner Right Image'},
        ),
        migrations.AlterModelOptions(
            name='homeourservice',
            options={'verbose_name': '5.1 Our Service ', 'verbose_name_plural': '5.1 Our Service '},
        ),
        migrations.AlterModelOptions(
            name='homestudentopenion',
            options={'verbose_name': '12. Student Openion ', 'verbose_name_plural': '12. Student Openion '},
        ),
        migrations.AlterModelOptions(
            name='our_service_text',
            options={'verbose_name': '5. Our Service Heading Text ', 'verbose_name_plural': '5. Our Service Heading Text '},
        ),
    ]
