# Generated by Django 4.2.11 on 2024-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0027_alter_all_category_card_data_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prather_Logo', models.ImageField(blank=True, null=True, upload_to='Deshboard/media/')),
            ],
            options={
                'verbose_name': '14. Our Partner Image ',
                'verbose_name_plural': '14. Our Partner Image ',
            },
        ),
    ]
